---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: kube-system
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: nginx-ingress
  rollback:
    enable: true
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: nginx-ingress
    version: 1.33.4
  values:
    controller:
      replicaCount: 2
      image:
        repository: quay.io/kubernetes-ingress-controller/nginx-ingress-controller-arm
        tag: 0.30.0
      config:
        ssl-protocols: "TLSv1.3 TLSv1.2"
        use-proxy-protocol: "false"
        proxy-body-size: "50m"
        use-forwarded-headers: "true"
        #
        # @CHANGEME - If you do not use Cloudflare, you can remove the next few lines
        #
        forwarded-for-header: "CF-Connecting-IP"
        # Cloudflare IP Addresses - Used to forward the real client IP address to the backend service
        # https://www.cloudflare.com/ips/
        proxy-real-ip-cidr: "103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,104.16.0.0/12,108.162.192.0/18,131.0.72.0/22,141.101.64.0/18,162.158.0.0/15,172.64.0.0/13,173.245.48.0/20,188.114.96.0/20,190.93.240.0/20,197.234.240.0/22,198.41.128.0/17,2400:cb00::/32,2606:4700::/32,2803:f800::/32,2405:b500::/32,2405:8100::/32,2a06:98c0::/29,2c0f:f248::/32"
      #
      # @CHANGEME - Update loadBalancerIP to the IP NginX will use.
      # It should match a IP Address you have in range for MetalLB
      #
      service:
        loadBalancerIP: 192.168.42.100
        externalTrafficPolicy: Local
      resources:
        requests:
          memory: 500Mi
          cpu: 25m
        limits:
          memory: 600Mi
    defaultBackend:
      enabled: false
