---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nzbget
  namespace: default
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: nzbget
  rollback:
    enable: true
  chart:
    repository: https://billimek.com/billimek-charts/
    name: nzbget
    version: 3.1.2
  values:
    image:
      repository: linuxserver/nzbget
      tag: v21.0-ls42
    timezone: "America/New_York"
    puid: 1000
    pgid: 100
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    persistence:
      config:
        enabled: true
        storageClass: "local-path"
      downloads:
        enabled: false
      extraMounts:
        - name: media
          claimName: nfs-media-pvc
    resources:
      requests:
        memory: 300Mi
        cpu: 25m
      limits:
        memory: 1000Mi
    #
    # @CHANGEME - Update the hostname to the node you want this deployed to
    #
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - k3s-worker-a
  valueFileSecrets:
  - name: "nzbget-helm-values"